### ISSUE TITLE
Output directory problem/confusion in run-sdm.R

### ISSUE THREAD

**Issue by elyons** [jcoliver/ebutterfly-sdm#1]
I tried running with <output> named "./output/12345" and the program failed due to the nested directory.  Error returned was 'could not open file 'output/images/output/12345-prediction.png'

Could the subdirectory and subsequent expected directories be created?

**Comment by jcoliver** [comment]
@elyons Changed so full directory specification is dictated by the user. i.e. removed the hard-coded output destination folders and instead require those paths (full or relative) be provided by whoever calls the script. Allows a check to see if output directories exist.

`Usage: Rscript --vanilla run-sdm.R <path/to/data/file> <output-file-prefix> <path/to/output/directory>`

Commit: bc6d41283ba0f428fb7b9a32d3a42b850c3ebdb7
