### ISSUE TITLE
[INFO522] How to run SDM

### ISSUE THREAD

**Issue by kensaku-okada** [jcoliver/ebutterfly-sdm#2]
Hello Dr Jeff

Could you tell me what I should do more to run the SDM commands? I installed R, RScript, and all of necessary packages listed in MEADME.md, but it did not work, returning the following errors.
![capture1](https://user-images.githubusercontent.com/6435299/30555674-115b908e-9c5d-11e7-884d-b6862f74ddb4.PNG)

I mainly run these commands, removing part of them.
Usage: Rscript --vanilla get-observation-data.R <taxon_id>
Usage: Rscript --vanilla run-sdm.R <path/to/data> <output-file-prefix>

**Comment by jcoliver** [comment]
For this notation, the text inside the < > characters is not literal, but a placeholder. For get-observation-data.R, you would need to use an actual taxon_id (an integer). For the run-sdm.R script, you would need:
- a path to a data file
- a prefix to use for output files
- a path to the output directory
I updated the README to include examples:
`Rscript --vanilla get-observation-data.R 60606`
`Rscript --vanilla run-sdm.R data/inaturalist/60606-iNaturalist.txt 60606 output/`
